[versions]
plugin-android = "8.1.2"
plugin-ktlint = "11.6.1"
plugin-maven = "0.22.0"

kotlin = "1.9.10"

coroutines = "1.7.3"
ksp = "1.9.10-1.0.13"
caseFormat = "0.2.0"
konsumeXml = "1.0"

appCompat = "1.6.1"
compose = "1.5.4"
composeCompiler = "1.5.3"
composeActivity = "1.8.0"
composeMultiplatform = "1.5.3"

test-junit = "1.1.5"

[libraries]
plugin-android = { module = "com.android.tools.build:gradle", version.ref = "plugin-android" }
plugin-ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "plugin-ktlint" }
plugin-maven = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "plugin-maven" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-ksp = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
plugin-compose-multiplatform = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "composeMultiplatform" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
ksp = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
caseFormat = { module = "com.fleshgrinder.kotlin:case-format", version.ref = "caseFormat" }
konsumeXml = { module = "com.gitlab.mvysny.konsume-xml:konsume-xml", version.ref = "konsumeXml" }

appCompat = { module = "androidx.appcompat:appcompat", version.ref = "appCompat" }
compose-activity = { module = "androidx.activity:activity-compose", version.ref = "composeActivity" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-ui-text = { module = "androidx.compose.ui:ui-text", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }

test-junit = { module = "androidx.test.ext:junit-ktx", version.ref = "test-junit" }

[bundles]
plugins = [
    "plugin-android",
    "plugin-ktlint",
    "plugin-maven",
    "plugin-kotlin",
    "plugin-ksp",
    "plugin-compose-multiplatform",
]